font_family Iosevka
background_opacity 0.9
clear_all_shortcuts yes
font_size 14
confirm_os_window_close 0
enable_audio_bell no
map ctrl+shift+/ search_scrollback
map ctrl+equal change_font_size current +2.0
map ctrl+minus change_font_size current -2.0
map ctrl+shift+c copy_to_clipboard
map ctrl+shift+v paste_from_clipboard
